name: rikulo_gap
version: 0.5.0
description: >
  Rikulo Gap is a bridge implementation in Dart language of the Apache Cordova mobile
  framework which enables developers to access native facilities of multiple
  mobile platforms using the HTML, CSS, and Dart.
authors:
- Henri Chen <henrichen@rikulo.org>
homepage: http://rikulo.org
dependencies:
  js:
    hosted: js
