name: rikulo_gap
version: 0.5.0
description: >
  Rikulo Gap is a bridge implementation of the Apache Cordova/PhoneGap mobile
  framework which enables developers to access native resources of multiple
  mobile platforms using the HTML, CSS, and Dart.
authors:
- Henri Chen <henrichen@rikulo.org>
homepage: http://rikulo.org
dependencies:
  js: any
  rikulo: any
  rikulo_commons: any
