name: rikulo_gap_test
version: 0.5.0
description: >
  Example that test the rikulo-gap and mobile Acclerometer.
authors:
- Henri Chen <henrichen@rikulo.org>
homepage: http://rikulo.org
dependencies:
  rikulo:
    git: git://github.com/rikulo/rikulo.git
  rikulo_gap:
    git: git://github.com/rikulo/rikulo-gap.git
  js:
    hosted: js
    version: 0.0.5